require 'slack-ruby-bot'
require 'shamebot/bot'
require 'shamebot/commands/shame'
require 'shamebot/commands/modify'
require 'shamebot/lib/setting'
require 'shamebot/lib/getting'
require 'wall_of_shame'
